FROM alpine:3.15

RUN apk update && apk upgrade
RUN apk add --no-cache nginx openssl

RUN mkdir -p /etc/nginx/ssl
RUN openssl req \
            -x509 -nodes -days 365 -newkey rsa:2048 \
            -out /etc/nginx/ssl/{{ inventory_hostname }}.crt \
            -keyout /etc/nginx/ssl/{{ inventory_hostname }}.key \
            -subj "/C=RU/ST=Moscow/L=Moscow/O=School21/OU=School21/CN={{ inventory_hostname }}/emailAddress=dredfort@student.21-school.ru"

RUN mkdir -p /var/www/html
RUN rm /etc/nginx/http.d/default.conf
COPY ./nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]