FROM debian:buster

RUN apt-get update -y

RUN apt-get install php7.3 -y
RUN apt-get install php-mysqli -y
RUN apt-get install php-fpm -y
RUN mkdir -p ./run/php/
COPY ./www.conf ./etc/php/7.3/fpm/pool.d/www.conf

ADD https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar ./wp-cli.phar
RUN chmod 777 ./wp-cli.phar
RUN mv ./wp-cli.phar ./usr/bin/wp
RUN wp core download \
    --allow-root \
    --path=./var/www/html/{{ inventory_hostname }}
COPY ./wp-config.conf ./wp-config.php

COPY ./site.tar.gz ./mysite/site.tar.gz
RUN tar -xzvf ./mysite/site.tar.gz
RUN rm ./mysite/site.tar.gz
RUN mkdir -p ./var/www/html/{{ inventory_hostname }}/{{ CLOUD_USER }}
RUN mv ./mysite/* ./var/www/html/{{ inventory_hostname }}/{{ CLOUD_USER }}
RUN rm -rf ./mysite

EXPOSE 9000

COPY ./entrypoint.sh ./entrypoint.sh
CMD bash ./entrypoint.sh